name: CICD_TEST
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
    paths: [ 'dbscripts/deploy/**' ]

  workflow_dispatch:
  
jobs:
  liquibase-action-test-1:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v2
      # note the below assumes that a host path or volume is mounted into the container at ./Docker (or action will fail) !!!
      
      - name: RUN 'LIQUIBASE STATUS IN A DOCKER CONTAINER'
        uses: docker://liquibase/liquibase:latest
        with:
          args: --url=${{ secrets.DL_SNOWFLAKE_URL }} --changeLogFile=./dbscripts/masterChangeLog.xml --username=${{ secrets.SNOWFLAKE_USERNAME }} --driver=${{ secrets.SF_DRIVER }} status -Dil_db_name=DEV_ENT_IL_CA_DB -Dgov_db_name=DEV_ENT_GOV_CA_DB --verbose

      - name: RUN 'LIQUIBASE updateSQL IN A DOCKER CONTAINER'
        uses: docker://liquibase/liquibase:latest
        with:
          args: --url=${{ secrets.DL_SNOWFLAKE_URL }} --changeLogFile=./dbscripts/masterChangeLog.xml --username=${{ secrets.SNOWFLAKE_USERNAME }} --driver=${{ secrets.SF_DRIVER }} updateSQL -Dil_db_name=DEV_ENT_IL_CA_DB -Dgov_db_name=DEV_ENT_GOV_CA_DB

      - name: LIQUIBASE RUN UPDATE
        uses: docker://liquibase/liquibase:latest
        with:
          args: --url=${{ secrets.DL_SNOWFLAKE_URL }} --changeLogFile=./ENT_DL_CA_DB/ENT_DL_CA_DB.xml --username=${{ secrets.SNOWFLAKE_USERNAME }} --driver=${{ secrets.SF_DRIVER }} update -Dil_db_name=DEV_ENT_IL_CA_DB -Dgov_db_name=DEV_ENT_GOV_CA_DB
